version: 2.1
orbs:
  irc: circleci/irc@0.2.0
  node: circleci/node@3.0.0
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - irc/notify:
          channel: deployment
          message: Build completed!
          nick: zeedas
          port: 6667
          server: 7c929776eb49.ngrok.io
workflows:
  your-workflow:
    jobs:
      - build